site_name: uenv and CPE Containers @ CUG 2025
# TODO: change to https://docs.cscs.ch when the time comes
site_url: https://eth-cscs.github.io/cug25-uenv

# provide a link to the docs in top RHS corner
repo_url: https://github.com/eth-cscs/cscs-docs
# provide a link to "edit this page" to each page
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
plugins:
  - search:
      pipeline:
        - trimmer
  - autorefs
nav:
  - Welcome: index.md
  - 'Tutorial': tutorial.md

theme:
  name: material
  language: en
  features:
    - content.code.copy
    # add an "edit this page" icon on each page
    - content.action.edit
    - navigation.indexes
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
    - content.code.annotate
  icon:
    # set the icon for "edit this page"
    edit: material/pencil
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/cscs-logo.png
  font:
    text: Roboto
    code: Roboto Mono
markdown_extensions:
  - admonition
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  # for captioning images
  - pymdownx.blocks.caption

extra_javascript:
 - javascripts/mathjax.js
 - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
