name: Build and Deploy MkDocs

on:
  push:
    branches: [main]  # or your default branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push to repo (for deploy-from-action)
      pages: write     # Required if deploying via GitHub Pages Action
      id-token: write  # Required for GitHub Pages deployment from Action

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs and dependencies
        run: |
          pip install -r requirements.txt

      - name: Build MkDocs
        run: mkdocs build

      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: tutorial slides
        working-directory: slides/tutorial
        run: |
          npm i -g @antfu/ni
          nci
          nr build --base /${{github.event.repository.name}}/slides/tutorial --out ../../site/slides/tutorial

      - name: paper slides
        working-directory: slides/paper
        run: |
          npm i -g @antfu/ni
          nci
          nr build --base /${{github.event.repository.name}}/slides/paper --out ../../site/slides/paper

      - name: cpe slides
        working-directory: slides/cpe
        run: |
          npm i -g @antfu/ni
          nci
          nr build --base /${{github.event.repository.name}}/slides/cpe --out ../../site/slides/cpe

      - run: ls -R ./site

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

