name: build-mkdocs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: mkdocs build -d site/docs
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site
          path: site/docs

